all:
	@cd fb;		make
	@cd vo;		make
	@cd venc;	make
	@cd vdec;	make
	@cd audio;	make
	@cd tde;	make
	@cd other;  make

clean:
	@cd fb;		make clean
	@cd vo;		make clean
	@cd venc;	make clean
	@cd vdec;	make clean
	@cd audio;	make clean
	@cd tde;	make clean
	@cd other;  make clean

distclean:
	@cd fb;		make distclean
	@cd vo;		make distclean
	@cd venc;	make distclean
	@cd vdec;	make distclean
	@cd audio;	make distclean
	@cd tde;	make distclean
	@cd other;  make distclean
